#!/usr/bin/env python
import logging
import plasTeX.Logging  # noqa: F401
logging.setLoggerClass(logging.Logger)

import argparse
import datetime
import chirun.plastex
import chirun.latex
import os
import shutil
import yaml
import shutil
import chirun
from chirun import mkdir_p
from chirun.item import load_item
from chirun import process
from chirun.theme import Theme
from chirun import oembed
from chirun.cli import Chirun, arg_parser
from pathlib import Path


logger = logging.getLogger('chirun')


def main():
    args = arg_parser().parse_args()

    extensions = [
        chirun.plastex.PlastexRunner,
    ]

    class Builder(Chirun, *extensions):
        pass

    mc = Builder(args)
    mc.build()

    print("Output written to {}".format(mc.build_dir.resolve()))


if __name__ == "__main__":
    main()
