name: Run the unit tests

# Controls when the workflow will run
on:
  push:
    branches: [ unittests, master ]
  pull_request:
    branches: [ unittests, master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PYTHON_COMMAND: python

jobs:
  build:
    runs-on: ubuntu-latest
    container: coursebuilder/chirun-base:dev
    
    defaults:
      run:
        working-directory: .
    
    steps:
      - uses: actions/checkout@v7.0.1

      - run: /venv/bin/pip install --upgrade setuptools pip
      
      - run: /venv/bin/pip install .
      
      - run: |
          . /venv/bin/activate
          make test
