name: Run the unit tests

# Controls when the workflow will run
on:
  push:
    branches: [ unittests, master, tmate-debug ]
  pull_request:
    branches: [ unittests, master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PYTHON_COMMAND: python3

jobs:
  build:
    runs-on: ubuntu-latest
    container: coursebuilder/chirun-base:dev
    
    defaults:
      run:
        working-directory: .
    
    steps:
      - uses: actions/checkout@v3

      - run: pip install --upgrade setuptools pip
      
      - run: pip install .

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
      
      - run: make test
